language: go
sudo: false
go: 1.7
node_js: 6.9.0
cache:
  directories:
  - "/node_modules"
install:
- ". $HOME/.nvm/nvm.sh"
- nvm install stable
- nvm use stable
- npm install -g "gulpjs/gulp#4.0"
- curl -sSL https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  | tar -zxf - -C /tmp/
- mv /tmp/hugo_${HUGO_VERSION}_linux_amd64/hugo_${HUGO_VERSION}_linux_amd64 /tmp/hugo
- rm -rf /tmp/hugo_${HUGO_VERSION}_linux_amd64
- export PATH="/tmp:$PATH"
script: npm install && gulp build:prod
after_success: |
  if [ -n "$GITHUB_API_KEY" ] && [ ${TRAVIS_PULL_REQUEST} == "false" ] && [ $TRAVIS_BRANCH == "test" ]; then
    cd ./public && cp ../CNAME ./CNAME
    git init
    git add .
    git -c user.name='storecorebot' -c user.email='travis@storecore.org' commit -m "build ${TRAVIS_COMMIT::8}"
    echo "Pushing content to GitHub"
    git push --force "https://storecorebot:${GITHUB_API_KEY}@github.com/storecore/test.storecore.io.git" master:gh-pages
  fi
env:
  global:
    secure: ege7j03tTuLWjnCsXPr8v1SPAv8/7IW+XVfHF8EphJKCIJ8u88/5xiq+8cuBaYR9DvtmF4JI9a2JQ3GQA8Kv9nF4HxyZKiSDpvgmXPxtLkUL/cx5zqDjZvaAS7VouY9TwOdbOlhpPttnCvML7qi7kx0bFaInGrv1C4KlOvW217ZqoQMno5kjzvR3dGz1JLKG5pHIoACsa7P+5jrtGxEsMejqV9cFahtHC4rhvNwqKUUOt0CE/23yqH5sXQFdUVTK7rUFbFAb2m60jiSLSx7HOyEFDCUmVZhmqPKQB7KUO9O7PfvutbBf6fI0UxhF04exKe6y5WBMfAPAjjSA9dFit5DedUZBMWhmc1V6jcmVICOwkpz9Hpe7KIx7uoYYKg6cuVPDtFPGpX3xwrrtPr1tfBSfJD+dGRa7dS0G3RILr2DB4kjxBM47sgytmK2RZmbP8KSDohx1KjrgNSl4EJDCtXo7XKFWkjnYmuYuD/bKs8wMlRuxlPXSnDLCaL9nxYP1+iN04waMEFvFaa2oyZQ2FDxbF6ICX3d69j1Oo0B6ryiG6j2Mxe3ZRCsADVNyGJcMwc1L7PCuC8j9uoSAxIaJXYQkvNm3RN1N6WAFfi7KnLS1KfxmG9IU8yveGk8xA7nOluyTGs8BwWlewaQZs3hHAMjRKXg+jsAywET3jvnf0bU=
