# safelist
# branches:
#   only:
#     - master

language: go
sudo: false
go: 1.7
node_js: 6.9.0
cache:
  directories:
  - /node_modules
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g "gulpjs/gulp#4.0"
  - curl -sSL https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz | tar -zxf - -C /tmp/
  - mv /tmp/hugo_${HUGO_VERSION}_linux_amd64/hugo_${HUGO_VERSION}_linux_amd64 /tmp/hugo
  - rm -rf /tmp/hugo_${HUGO_VERSION}_linux_amd64
  - export PATH="/tmp:$PATH"
script: npm install && gulp build:prod
after_success: |
  if [ -n "$GITHUB_API_KEY" ] && [ ${TRAVIS_PULL_REQUEST} == "false" ] && [ $TRAVIS_BRANCH == "test" ]; then
    GIT_COMMIT=`git rev-parse --short HEAD`
    cd ./public && cp ../CNAME ./CNAME
    git init > /dev/null 2>&1
    git add .
    git -c user.name='Travis-CI' -c user.email='travis@storecore.io' commit -m "build ${GIT_COMMIT}" > /dev/null 2>&1
    echo "Pushing content to GitHub"
    git push --force --quiet "https://${GITHUB_API_KEY}@github.com/storecore/test.storecore.io.git" master:gh-pages > /dev/null 2>&1
  fi
