language: go
sudo: false
go: 1.7
node_js: 6.9.0
cache:
  directories:
  - "/node_modules"
install:
- ". $HOME/.nvm/nvm.sh"
- nvm install stable
- nvm use stable
- npm install -g "gulpjs/gulp#4.0"
- curl -sSL https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  | tar -zxf - -C /tmp/
- mv /tmp/hugo_${HUGO_VERSION}_linux_amd64/hugo_${HUGO_VERSION}_linux_amd64 /tmp/hugo
- rm -rf /tmp/hugo_${HUGO_VERSION}_linux_amd64
- export PATH="/tmp:$PATH"
script: npm install && gulp build:prod
after_success: |
  if [ -n "$GITHUB_API_KEY" ] && [ ${TRAVIS_PULL_REQUEST} == "false" ] && [ $TRAVIS_BRANCH == "master" ]; then
    cd ./public && cp ../CNAME ./CNAME
    git init > /dev/null
    git add .
    git -c user.name='storecorebot' -c user.email='travis@storecore.org' commit --quiet -m "build ${TRAVIS_COMMIT::8}"
    echo "Pushing content to GitHub"
    git push --force --quiet "https://storecorebot:${GITHUB_API_KEY}@github.com/storecore/test.storecore.io.git" master:gh-pages > /dev/null
  fi
env:
  global:
  - secure: jljDDwtEZEgU/lzk4vsYuOWUSLJlSszjBmNhdFWELn54F/eBdhp5ZbUM9kLzHWZz8VkE+RQqCqkhH/gFb7oJnhGld5dmqKZwI14qCw5XWhvtQkFmJ3nF/XcpEg7e8L9YsTvMeWaaZ36xbTvi4/HEbgQYtomHmmo1Q+JoXEyEwlMAdxlr4YuhnoaYyGZqzUAW9IlhFU2KccwS1YVnbBR+O5DdDTG31lx04IN1Y8K00SJqCFv18bLf6ATEUv+7PBt7hpPV/cy1t8tEKunnk9CarN2xn8WrZerVUv2mHZqPv0iFa8bemTbURyJ3sS2wbsQmUKTLJ8Nx819Mf95+skTtuP/VP5UqeGU06fS49JdkhgJb8EBlYYkEzBCdPuUh2agoIDPO/sWRhHMjzZj6vLrHgORzYPoZxbpcuFaO8d7qUC2TtPz4RBpD73tZ2BoZv3tDOY4NT7PcVfHN9db8UQqKJoTYRVFNIdFDhbaPhUYKhCyiUZuK8WSrgxx3P0FrItH74o3CQkh7o2N/EiKsWODhZjPBMofQkaGnq5AxXJZ0I5IqnjXDQrbY4ArWA9J5vDxhC8WrVyYKAVdFjYsJ7B52BepyEn+QHXlNdYc2qf2OuLQhUtjS7EH0mIWlWFw77kZ/pDobYlPxdB+smEg2DB8fKNTUT6MSHR/p7N1DfeCLfm0=
