language: python
python:
  - "3.6"
sudo: false
install: "pip install ampersand"
script: "ampersand serve"
after_success: |
  if [ ${TRAVIS_PULL_REQUEST} == "false" ]; then
    ls -la
    find . -type f -name "*.html" -print0 | xargs -0 sed -i '' -e 's/ &amp;nbsp;/\ /g; s/&nbsp;/\ /g; s/&amp;/\&/g; s/&lt;/\</g; s/&gt;/\>/g; s/&quot;/\"/g; s/&#39;/\'"'"'/g'
  fi
deploy:
  provider: pages
  local_dir: _site
  email: travis@storecore.org
  name: storecorebot
  fqdn: test.storecore.io
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
notifications:
  slack:
    secure: EmmhXZ/pIC4q2nORnhvXy2X2ODSaazRD/j/4iSCRQ9nwvbPsWKELUvvN4pD1U9zjyVcTyNKpn0uIVv6O9A1iRL02m8jpodVd+F+TDALV2Yrbf44a4jYzCe7AcaIoAtbVSCEUMQz+0jq4vFHb8EwG1nR+/K6htk6M+KxD8vRrXXC999F+l50DmzFMuuR5Jdy15e95QjkX2OhzRndkr7sJO3PrvkrcQB1UeKrYn8jnpHz7ArGB9DpZ+nf5CuraCEkn5SmKhB1NinYj/3oK5B9m7rGSBD/8CKMiFnKK7pbYCPaAVwQorDTk2UV7T2I73d1WTqAQ3l2oUgJ3WL2he/K7fEp9vUezD7JyGuxDcfMojgMwOW4njj7MaXc52uZtXldbzyJjtwGa3FKfTfXfhGYGRgYJ6i5tqdv82VYOG63ITT/PPuhF5RjcHIVetGttpxxae14/067fmaPm7Mu6B4KPfqNn4LmaE0b30iLJdnxiUN0/vW6pXUaWxdlAStvvyTnpHnbecUIqk4pEH1NbvzmoQT49EVSTjynJH9gtwfEXkYeediCWeKSNTQYSX4WvmBq5JuE2p1mX2Iug8wrxRsqezkva7eSbbigoeyIfNVxRWYj27ZUkGJQE9Zt/z7WNnTl+TApT/4seqGM02k4TEhG/lKIVKL0WOaGZp0Cxlr1ECiU=
