baseurl = "."
languageCode = "en-US"
title = "StoreCore"
theme = "storecore-theme"
metadataformat = "yaml"
canonifyurls = true
pluralizeListTitles = false

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "storeore.io"
	description = "StoreCore - "
	copyright = "Released under the Apache 2 license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/storecore/core"

	version = "0.0.1"
	logo = "images/autobot_logo.svg"
	favicon = "images/autobot_logo.svg"

	permalink = "#"

	# Custom assets
	custom_css  = [
	  "stylesheets/dropdown.css"
	]
	custom_js   = [
	  "javascripts/lunr.min.js",
	  "javascripts/version.js"
	]

	# Syntax highlighting theme
	highlight_css  = ""

	dateform = "Jan 2, 2006"
	dateformfull = "Mon Jan 2 2006 15:04:05 MST"

[params.recent_posts]
  enable = true
  title = "From our blog"
  subtitle = "Pellen"

[params.palette]
	primary = "pink"
	accent  = "pink"

[params.font]
	text = "Roboto"
	code = "Roboto Mono"

[social]
	twitter = "magneticio"
	github  = "magneticio/vamp"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

# Top Menu Items
[[menu.main]]
	name   = "Why use StoreCore?"
	url    = "/why-use-vamp/why-use-vamp/"
	identifier = "why-use-vamp-top"
	weight = 10

[[menu.main]]
	name   = "Documentation"
	url    = "/documentation/how-vamp-works/architecture-and-components/"
	weight = 20

[[menu.main]]
	name   = "Resources"
	url    = "/resources/downloads/"
	weight = 30

[[menu.main]]
	name   = "Blog"
	url    = "/blog/"
	weight = 40

[[menu.main]]
	name   = "Support"
	url    = "/support/"
	weight = 50

# Side Menu Items, Parent should match the identifier of the Top Menu Item
[[menu.main]]
	name = "Use cases"
	url = "/why-use-vamp/use-cases/use-cases"
	parent = "why-use-vamp-top"
	weight = 10

[[menu.main]]
	name  = "Vamp compared to..."
	url   = "/why-use-vamp/vamp-compared-to/proxies-and-load-balancers/"
	parent = "why-use-vamp-top"
	weight = 30

[[menu.main]]
	name	= "How Vamp works"
	url = "/documentation/how-vamp-works/architecture-and-components/"
	parent = "Documentation"
	weight = 10

[[menu.main]]
	name = "Using Vamp"
	url = "documentation/using-vamp/artifacts/"
	parent = "Documentation"
	weight = 20

[[menu.main]]
	name = "Tutorials"
	url = "/documentation/tutorials/overview"
	parent = "Documentation"
	weight = 30

[[menu.main]]
	name = "Install"
	identifier = "Installation"
	url = "/documentation/installation/overview"
	parent = "Documentation"
	weight = 40

[[menu.main]]
	name = "API documentation"
	identifier = "API"
	url = "/documentation/api/api-reference"
	parent = "Documentation"
	weight = 60

[[menu.main]]
	name = "CLI documentation"
	identifier = "CLI"
	url = "/documentation/cli/cli-reference/"
	parent = "Documentation"
	weight = 70

[[menu.main]]
	name = "Release notes"
	url = "/documentation/release-notes/"
	parent = "Documentation"
	weight = 80
