baseurl = "."
languageCode = "en-US"
title = "StoreCore"
theme = "storecore"
metadataformat = "yaml"
canonifyurls = true
pluralizeListTitles = false

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "storeore.io"
	description = "StoreCore - "
	copyright = "Released under the Apache 2 license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/storecore/core"

	version = "0.0.1"
	logo = "images/autobot_logo.svg"
	favicon = "images/autobot_logo.svg"

	permalink = "#"

	# Custom assets
	custom_css  = [
	  "stylesheets/dropdown.css"
	]
	custom_js   = [
	  "javascripts/lunr.min.js",
	  "javascripts/version.js"
	]

	# Syntax highlighting theme
	highlight_css  = ""

	dateform = "Jan 2, 2006"
	dateformfull = "Mon Jan 2 2006 15:04:05 MST"

[params.recent_posts]
  enable = true
  title = "From our blog"
  subtitle = "Pellen"

[social]
	twitter = "storecorehq"
	github  = "storecore"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[[menu.main]]
	name   = "Documentation"
	url    = "/documentation/getting-started/intro"
	weight = 10


# Side Menu Items, Parent should match the identifier of the Top Menu Item
[[menu.main]]
	name = "Getting Started"
	identifier = "Started"
	url = "/documentation/getting-started/intro"
	parent = "Documentation"
	weight = 40

	[[menu.main]]
	name = "API documentation"
	identifier = "API"
	url = "/documentation/api/api-reference"
	parent = "Documentation"
	weight = 60
