---
baseurl: "."
languageCode: "en-US"
title: "StoreCore"
theme: "storecore"
metadataformat: "yaml"
canonifyurls: true
pluralizeListTitles: false
disqusShortname: "storecore"
permalinks:
  blog: /:title/
# Enable Google Analytics by entering your tracking id
googleAnalytics: ""
related_content_limit: 4

params:
  # General information
  author: "storeore.io"
  description: "StoreCore - "
  copyright: "Released under the Apache 2 license"

  # Repository
  provider: "GitHub"
  repo_url: "https://github.com/storecore/core"

  version: "0.0.1"
  logo: "images/autobot_logo.svg"
  favicon: "images/autobot_logo.svg"

  # Custom assets
  custom_css:
    - "stylesheets/dropdown.css"
  custom_js:
    - "javascripts/lunr.min.js"
    - "javascripts/version.js"

  # Syntax highlighting theme
  highlight_css: ""

  dateform: "Jan 2, 2006"
  dateformfull: "Mon Jan 2 2006 15:04:05 MST"

  comments: true

social:
  twitter: "storecorehq"
  github: "storecore"

blackfriday:
  smartypants: true
  fractions: true
  smartDashes: true
  plainIDAnchors: true

# Top Menu Items
menu:
  main:
      - Name: "Home"
        URL: "/"
        Weight: 10
      - Name: "Pricing"
        URL: "/pricing/"
        Weight: 30
      - Name: "Release Schedule"
        URL: "/releases/"
        Weight: 40
      - Name: "Resources"
        URL: "/documentation/getting-started/intro"
        Weight: 50
      - Name: "Blog"
        URL: "/blog/"
        Weight: 60
      - Name: "Contact"
        URL: "/contact/"
        Weight: 70
# Sub Menu Items
      - Name: "Getting Started"
        Identifier: "Started"
        URL: "/documentation/getting-started/intro"
        parent: "Resources"
        Weight: 10
      - Name: "API Documentation"
        Identifier: "API"
        URL: "/documentation/api/api-reference"
        parent: "Resources"
        Weight: 20
